### ISSUE TITLE
participant checklistOptions broken

### ISSUE THREAD

**Issue by WGHmajo** [gregwalker-pexip/workflowOne#1]
Hi

it seems checklistOptions seems broken due to: 
`@pexip_plugin-api.js?v=b310d2a0:22 emit with error for observer Anonymous {signal: 'AnonymousSignal', error: TypeError: participants.map is not a function`

checking:
`console.log("Checklist Options: ", checklistOptions);`

returns in JS console:
`Checklist Options:  undefined`

therefore "Manage Participants" functionality is broken as well

used webapp3:
Version: 5.0.0+4cb0f5f57
Plugin API Version: 18.0.0

any ideas or tips on how to fix this ?

Regards
Joerg

**Comment by gregwalker-pexip** [comment]
Hi Jeorg,

Refer to https://developer.pexip.com/docs/plugins/webapp-3/plugin-api/visual-elements

My lab is using latest beta build as per below but it should work on v18.0 dependencies 
Version: 6.0.0+bc6f3c1cf  
Plugin API Version: 19.1.0

You can also refer to https://github.com/gregwalker-pexip/in-meeting-phonebook-plugin which is a simpler more recent example.

TIP: Make sure your dependencies are set correctly in your package.json

Also you can post queries on https://community.pexip.com/ which has a broader audience 

Regards,

Greg
